### ISSUE TITLE
failure to load webppl in Safari and Firefox

### ISSUE THREAD

**Issue by hawkrobe** [forestdb/forestdb.org#6]
While the church models seem to work just fine across browsers, @mhtess pointed out that webppl code boxes will not run in Safari. I also tried it in Firefox and got the same error message. 

Looks like the error actually happens at page load rather than when actually running the code box. I've pasted the Safari message below. Firefox simply says "TypeError: setting a property that has only a getter. (webppl.min.js, line 37)" 

```
[Error] TypeError: Attempted to assign to readonly property.
    (anonymous function) (webppl.min.js, line 37)
    (anonymous function) (webppl.min.js, line 39)
    s (webppl.min.js, line 1)
    e (webppl.min.js, line 1)
    global code (webppl.min.js, line 1)
```

**Comment by stuhlmueller** [comment]
Thanks for reporting - I'll look into it.

(This isn't specific to Forest -- same behavior on webppl.org and dippl.org.)

**Comment by hawkrobe** [comment]
More info from firebug: the problem is pinpointed to setting the global property in the `requireHeader` function in main.js:

```
function requireHeader(path) {        
  var header = require(path)(env);    
  for(var prop in header) {
    if(header.hasOwnProperty(prop)){
      global[prop]=header[prop] // <- Error: setting a property that has only a getter
    }
  }
}
```

**Comment by MinervaDTaylor** [comment]
WOW!!! 
This is the most wonderful thing i have ever experience and i need to share this great testimony.
About how i get my ex back after a breakup.
I never believed it, because i never heard nor learnt anything about it before. 
My name is Minerva D. Taylor from UK
My boyfriend of a 2year just broke up with me and am 28 weeks pregnant. I have cried my self to sleep most of the nights and don’t seem to concentrate during lectures sometimes I stay awake almost all night thinking about him and start to cry all over again. Because of this I end up not having energy for my next day’s classes, my attendance has dropped and am always in uni and on time. Generally he is a very nice guy, he ended it because he said we were arguing a lot and not getting along. He is right we’ve been arguing during the pregnancy a lot. After the break up I kept ringing him and telling him I will change. I am in love with this guy and he is the best guy I have ever been with. I’m still hurt and in disbelief when he said he didn’t have any romantic feelings towards me anymore that hurt me faster than a lethal syringe. He texts me once and then mainly to check up on how am doing with the pregnancy, he is supportive with it but it’s not fair on me, him texting me as I just want to grieve the pain and not have any stress due to the pregnancy. i was really upset and i needed help, so i searched for help online and I came across a website that suggested that Dr Adams can help solve marital problems, restore broken relationships and so on. So I felt I should give him a try. I contacted him and he told me what to do and i did it then he did a spell for me. 28 hours later, my boyfriend came to me and apologized for the wrongs he did and promise never to do it again. Ever since then, everything has returned back to normal. I and my boyfriend are living together happily again.. All thanks to Dr Adams. as it is a place to resolve marriage/relationship issues, do you want to be sure if your spouse is being faithful to you or Do you want your Ex to come back to you Contact.: E-mail: Adamsusmanultimate@gmail.com or call/Whats-app: +2348160153829 save your crumbling home and change of grades its 100% safe. I suggest you contact him. He will not disappoint you.
